"""Render logical datasets as a gnuplot dashboard."""

import math
import os
from pathlib import Path
import shutil
import tempfile


_GRAPH_TYPE_ORDER = {
    "residual": 0,
    "field_min_max": 1,
    "scalar_time_series": 2,
    "vector_time_series": 3,
    "patch_y_plus": 4,
}
_STAGING_PREFIX = ".ofgs-generation-"


class AtomicPublicationError(RuntimeError):
    """Raised before publication when atomic replacement is not safe."""


def _dataset_order(dataset):
    return (
        _GRAPH_TYPE_ORDER.get(dataset.graph_type, len(_GRAPH_TYPE_ORDER)),
        dataset.title.casefold(),
        dataset.title,
    )


def _quote(text):
    return str(text).replace("\\", "\\\\").replace("'", "\\'")


def _number(value):
    return format(value, ".15g")


def _data_block(block_name, x_axis, values):
    lines = [f"${block_name} << EOD"]
    lines.extend(f"{_number(x)} {_number(y)}" for x, y in zip(x_axis, values))
    lines.append("EOD")
    return lines


def _graph_lines(dataset, graph_index, compact_axes=False):
    lines = []
    plot_parts = []
    for series_index, (name, values) in enumerate(dataset.series.items()):
        block_name = f"data_{graph_index}_{series_index}"
        lines.extend(_data_block(block_name, dataset.x_axis, values))
        plot_parts.append(
            f"${block_name} with lines title '{_quote(name)}'"
        )

    graph_id = graph_index + 1
    lines.append(f"set title '[{graph_id:02d}] {_quote(dataset.title)}'")
    lines.append(f"set xlabel '{_quote(dataset.x_axis_title)}'")
    if compact_axes:
        lines.append('set format x "%.3g"')
        lines.append('set format y "%.3g"')
    if dataset.graph_type == "residual":
        lines.append("set logscale y")
    else:
        lines.append("unset logscale y")
    lines.append(f"plot {', '.join(plot_parts)}")
    lines.append("")
    return lines


def _standalone_lines(dataset, graph_index):
    lines = [
        "# Monitor script generated by OFGS",
        "",
        "set terminal qt size 1600,900",
        "set grid",
        "",
    ]
    lines.extend(_graph_lines(dataset, graph_index))
    lines.append('if (!exists("LIVE_MODE")) pause mouse close')
    return lines


def _write_standalone_graphs(graphs_path, datasets):
    """Write one complete graph set into an unpublished staging directory."""
    graphs_path.mkdir(parents=True)
    index_lines = []
    graph_names = set()
    for graph_index, dataset in enumerate(datasets):
        graph_id = graph_index + 1
        graph_number = f"{graph_id:02d}"
        graph_name = f"{graph_number}.gp"
        script_lines = _standalone_lines(dataset, graph_index)
        (graphs_path / graph_name).write_text("\n".join(script_lines))
        graph_names.add(graph_name)
        index_lines.append(f"{graph_number} {dataset.title}")

    (graphs_path / "index.txt").write_text("\n".join(index_lines) + "\n")
    return graph_names


def _numbered_graphs(graphs_path):
    if not graphs_path.is_dir():
        return []
    return sorted(
        path
        for path in graphs_path.glob("*.gp")
        if path.stem.isdigit()
    )


def _backup_current_output(case_path, backup_path):
    """Copy the published output so a failed commit can be rolled back."""
    backup_path.mkdir()
    monitor_path = case_path / "monitor.gp"
    if monitor_path.is_file():
        shutil.copy2(monitor_path, backup_path / "monitor.gp")

    graphs_path = case_path / "graphs"
    backup_graphs = backup_path / "graphs"
    backup_graphs.mkdir()
    if (graphs_path / "index.txt").is_file():
        shutil.copy2(graphs_path / "index.txt", backup_graphs / "index.txt")
    for script_path in _numbered_graphs(graphs_path):
        shutil.copy2(script_path, backup_graphs / script_path.name)


def _filesystem_device(path):
    return path.stat().st_dev


def _probe_atomic_graph_replacement(graphs_path, staging_path):
    """Verify rename compatibility using the exact publication directories."""
    probe_source = staging_path / "graphs" / ".ofgs-atomic-probe"
    probe_destination = graphs_path / f".ofgs-atomic-probe-{staging_path.name}"
    if probe_destination.exists() or probe_destination.is_symlink():
        raise AtomicPublicationError(
            "OFGS error: graphs/ contains a conflicting atomic-publication "
            "probe file; generation was not published."
        )

    probe_source.touch()
    try:
        os.replace(probe_source, probe_destination)
    except OSError as error:
        if probe_source.exists():
            probe_source.unlink()
        raise AtomicPublicationError(
            "OFGS error: graphs/ cannot accept same-filesystem atomic "
            "replacement from the case staging area; generation was not "
            "published."
        ) from error

    try:
        probe_destination.unlink()
    except OSError as error:
        raise AtomicPublicationError(
            "OFGS error: the graphs/ atomic-publication probe could not be "
            "removed; generation was not published."
        ) from error


def _validate_atomic_layout(case_path, staging_path):
    """Reject graph destinations that cannot use same-filesystem replacement."""
    graphs_path = case_path / "graphs"
    if graphs_path.is_symlink():
        raise AtomicPublicationError(
            "OFGS error: graphs/ is a symlink; atomic publication requires "
            "a real directory inside the OpenFOAM case."
        )
    if graphs_path.exists() and not graphs_path.is_dir():
        raise AtomicPublicationError(
            "OFGS error: graphs/ exists but is not a directory; generation "
            "was not published."
        )

    graph_destination = graphs_path if graphs_path.exists() else case_path
    if _filesystem_device(graph_destination) != _filesystem_device(
        staging_path / "graphs"
    ):
        raise AtomicPublicationError(
            "OFGS error: graphs/ is on a different filesystem from the case "
            "staging area; atomic publication is unavailable."
        )
    if graphs_path.exists():
        _probe_atomic_graph_replacement(graphs_path, staging_path)


def _restore_previous_output(case_path, backup_path, graphs_existed):
    """Restore the last published files after a commit-time failure."""
    graphs_path = case_path / "graphs"
    backup_graphs = backup_path / "graphs"
    graphs_path.mkdir(exist_ok=True)
    previous_graph_names = {
        path.name for path in _numbered_graphs(backup_graphs)
    }
    for script_path in _numbered_graphs(backup_graphs):
        os.replace(script_path, graphs_path / script_path.name)

    monitor_path = case_path / "monitor.gp"
    backup_monitor = backup_path / "monitor.gp"
    if backup_monitor.is_file():
        os.replace(backup_monitor, monitor_path)
    elif monitor_path.is_file() or monitor_path.is_symlink():
        monitor_path.unlink()

    index_path = graphs_path / "index.txt"
    backup_index = backup_graphs / "index.txt"
    if backup_index.is_file():
        os.replace(backup_index, index_path)
    elif index_path.is_file() or index_path.is_symlink():
        index_path.unlink()

    # The previous index is active again. New-only scripts are now unreferenced.
    for script_path in _numbered_graphs(graphs_path):
        if script_path.name not in previous_graph_names:
            script_path.unlink()

    if not graphs_existed:
        try:
            graphs_path.rmdir()
        except OSError:
            pass


def _publish_generation(case_path, staging_path, graph_names):
    """Atomically publish staged files, using the index as the commit marker."""
    graphs_path = case_path / "graphs"
    staged_graphs = staging_path / "graphs"
    backup_path = staging_path / "previous"
    graphs_existed = graphs_path.is_dir()
    _validate_atomic_layout(case_path, staging_path)
    _backup_current_output(case_path, backup_path)

    try:
        graphs_path.mkdir(exist_ok=True)
        for graph_name in sorted(graph_names):
            os.replace(staged_graphs / graph_name, graphs_path / graph_name)

        os.replace(staging_path / "monitor.gp", case_path / "monitor.gp")
        os.replace(staged_graphs / "index.txt", graphs_path / "index.txt")

        # The new index is now active. Remove only scripts it does not name.
        for script_path in _numbered_graphs(graphs_path):
            if script_path.name not in graph_names:
                script_path.unlink()
    except BaseException:
        _restore_previous_output(case_path, backup_path, graphs_existed)
        raise


def _remove_abandoned_staging(case_path):
    """Remove staging directories left by a previously crashed generator."""
    for staging_path in case_path.glob(f"{_STAGING_PREFIX}*"):
        if staging_path.is_dir() and not staging_path.is_symlink():
            try:
                shutil.rmtree(staging_path)
            except PermissionError:
                # A crashed generator owned by another collaborator may have
                # left a private TemporaryDirectory. It is safe to ignore: the
                # next generation uses a unique staging path.
                continue


def write_monitor(case_path, datasets):
    """Generate ``monitor.gp`` from graph-ready dataset objects."""
    _remove_abandoned_staging(case_path)
    datasets = sorted(
        list(datasets),
        key=_dataset_order,
    )
    if not datasets:
        return

    lines = [
        "# Monitor script generated by OFGS",
        "",
        "set terminal qt size 1600,900",
        "set grid",
        "",
    ]

    graph_count = len(datasets)
    columns = math.ceil(math.sqrt(graph_count))
    rows = math.ceil(graph_count / columns)
    if graph_count > 1:
        lines.extend((f"set multiplot layout {rows},{columns}", ""))

    for graph_index, dataset in enumerate(datasets):
        lines.extend(_graph_lines(dataset, graph_index, compact_axes=True))

    if graph_count > 1:
        lines.extend(("unset multiplot", ""))
    lines.append('if (!exists("LIVE_MODE")) pause mouse close')

    with tempfile.TemporaryDirectory(
        prefix=_STAGING_PREFIX,
        dir=case_path,
    ) as temporary_directory:
        staging_path = Path(temporary_directory)
        (staging_path / "monitor.gp").write_text("\n".join(lines))
        graph_names = _write_standalone_graphs(
            staging_path / "graphs",
            datasets,
        )
        _publish_generation(case_path, staging_path, graph_names)
